# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdmintest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_admintest(self):
    # Test name: admintest
    # Step # | name | target | value
    # 1 | open | /admin/ | 
    self.driver.get("https://iqa.tmax-superapp.com/admin/")
    # 2 | setWindowSize | 1627x944 | 
    self.driver.set_window_size(1627, 944)
    # 3 | click | name=horizontal-form-name | 
    self.driver.find_element(By.NAME, "horizontal-form-name").click()
    # 4 | type | name=horizontal-form-name | admin
    self.driver.find_element(By.NAME, "horizontal-form-name").send_keys("admin")
    # 5 | click | name=horizontal-form-email | 
    self.driver.find_element(By.NAME, "horizontal-form-email").click()
    # 6 | type | name=horizontal-form-email | tmax@23
    self.driver.find_element(By.NAME, "horizontal-form-email").send_keys("tmax@23")
    # 7 | click | css=.passwordIcon > path:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".passwordIcon > path:nth-child(2)").click()
    # 8 | click | css=.pf-c-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".pf-c-button").click()
    # 9 | click | css=.select-main-menu > .pf-c-menu__item-main > .pf-c-menu__item-text | 
    self.driver.find_element(By.CSS_SELECTOR, ".select-main-menu > .pf-c-menu__item-main > .pf-c-menu__item-text").click()
    # 10 | click | id=호스트 OS | 
    self.driver.find_element(By.ID, "호스트 OS").click()
    # 11 | click | id=머신 | 
    self.driver.find_element(By.ID, "머신").click()
    # 12 | click | id=컴퓨트 | 
    self.driver.find_element(By.ID, "컴퓨트").click()
    # 13 | click | id=네트워크 | 
    self.driver.find_element(By.ID, "네트워크").click()
    # 14 | click | css=#\C2A4\D1A0\B9AC\C9C0 > .pf-c-accordion__toggle-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\C2A4\\D1A0\\B9AC\\C9C0 > .pf-c-accordion__toggle-text").click()
    # 15 | click | id=모니터링 | 
    self.driver.find_element(By.ID, "모니터링").click()
    # 16 | click | id=관리 | 
    self.driver.find_element(By.ID, "관리").click()
    # 17 | click | id=호스트 OS | 
    self.driver.find_element(By.ID, "호스트 OS").click()
    # 18 | click | css=#\D638\C2A4\D2B8\ OS .link-style:nth-child(1) .pf-c-menu__item-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\D638\\C2A4\\D2B8\\ OS .link-style:nth-child(1) .pf-c-menu__item-text").click()
    # 19 | mouseOver | css=#\D638\C2A4\D2B8\ OS .link-style:nth-child(1) .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#\\D638\\C2A4\\D2B8\\ OS .link-style:nth-child(1) .pf-c-menu__item-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 20 | mouseOut | css=.pf-m-focus .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 21 | click | id=호스트 OS | 
    self.driver.find_element(By.ID, "호스트 OS").click()
    # 22 | click | id=호스트 OS | 
    self.driver.find_element(By.ID, "호스트 OS").click()
    # 23 | click | css=#\D638\C2A4\D2B8\ OS .link-style:nth-child(2) .pf-c-menu__item-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\D638\\C2A4\\D2B8\\ OS .link-style:nth-child(2) .pf-c-menu__item-text").click()
    # 24 | mouseOver | css=#\D638\C2A4\D2B8\ OS .link-style:nth-child(2) .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#\\D638\\C2A4\\D2B8\\ OS .link-style:nth-child(2) .pf-c-menu__item-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 25 | mouseOut | css=.pf-m-focus .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 26 | click | css=#\D638\C2A4\D2B8\ OS .link-style:nth-child(3) .pf-c-menu__item-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\D638\\C2A4\\D2B8\\ OS .link-style:nth-child(3) .pf-c-menu__item-text").click()
    # 27 | click | id=머신 | 
    self.driver.find_element(By.ID, "머신").click()
    # 28 | click | xpath=//dd[@id='머신']/div/div/div/ul/a/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'머신\']/div/div/div/ul/a/li/button/span/span").click()
    # 29 | click | xpath=//dd[@id='머신']/div/div/div/ul/a[2]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'머신\']/div/div/div/ul/a[2]/li/button/span/span").click()
    # 30 | click | xpath=//dd[@id='머신']/div/div/div/ul/a[3]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'머신\']/div/div/div/ul/a[3]/li/button/span/span").click()
    # 31 | mouseOver | xpath=//dd[@id='머신']/div/div/div/ul/a[3]/li/button/span/span | 
    element = self.driver.find_element(By.XPATH, "//dd[@id=\'머신\']/div/div/div/ul/a[3]/li/button/span/span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 32 | mouseOut | css=.pf-m-focus .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 33 | click | id=컴퓨트 | 
    self.driver.find_element(By.ID, "컴퓨트").click()
    # 34 | click | xpath=//dd[@id='컴퓨트']/div/div/div/ul/a/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'컴퓨트\']/div/div/div/ul/a/li/button/span/span").click()
    # 35 | click | css=#\B124\D2B8\C6CC\D06C > .pf-c-accordion__toggle-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\B124\\D2B8\\C6CC\\D06C > .pf-c-accordion__toggle-text").click()
    # 36 | click | xpath=//dd[@id='네트워크']/div/div/div/ul/a/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'네트워크\']/div/div/div/ul/a/li/button/span/span").click()
    # 37 | mouseOver | xpath=//dd[@id='네트워크']/div/div/div/ul/a/li/button/span/span | 
    element = self.driver.find_element(By.XPATH, "//dd[@id=\'네트워크\']/div/div/div/ul/a/li/button/span/span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 38 | mouseOut | css=.pf-m-focus .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 39 | click | xpath=//dd[@id='네트워크']/div/div/div/ul/a[2]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'네트워크\']/div/div/div/ul/a[2]/li/button/span/span").click()
    # 40 | mouseOver | xpath=//dd[@id='네트워크']/div/div/div/ul/a[2]/li/button/span/span | 
    element = self.driver.find_element(By.XPATH, "//dd[@id=\'네트워크\']/div/div/div/ul/a[2]/li/button/span/span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 41 | mouseOut | css=.pf-m-focus .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 42 | click | css=#\C2A4\D1A0\B9AC\C9C0 > .pf-c-accordion__toggle-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\C2A4\\D1A0\\B9AC\\C9C0 > .pf-c-accordion__toggle-text").click()
    # 43 | click | xpath=(//button[@type='button'])[26] | 
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[26]").click()
    # 44 | mouseOver | xpath=(//button[@type='button'])[26] | 
    element = self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[26]")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 45 | mouseOut | css=.pf-m-focus > .pf-c-menu__item | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 46 | click | xpath=//dd[@id='스토리지']/div/div/div/ul/a[2]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'스토리지\']/div/div/div/ul/a[2]/li/button/span/span").click()
    # 47 | click | css=#\BAA8\B2C8\D130\B9C1 > .pf-c-accordion__toggle-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\BAA8\\B2C8\\D130\\B9C1 > .pf-c-accordion__toggle-text").click()
    # 48 | click | xpath=//dd[@id='모니터링']/div/div/div/ul/a/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'모니터링\']/div/div/div/ul/a/li/button/span/span").click()
    # 49 | mouseOver | xpath=//dd[@id='모니터링']/div/div/div/ul/a[2]/li/button/span/span | 
    element = self.driver.find_element(By.XPATH, "//dd[@id=\'모니터링\']/div/div/div/ul/a[2]/li/button/span/span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 50 | click | xpath=//dd[@id='모니터링']/div/div/div/ul/a[2]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'모니터링\']/div/div/div/ul/a[2]/li/button/span/span").click()
    # 51 | mouseOver | xpath=//dd[@id='모니터링']/div/div/div/ul/a[3]/li/button/span/span | 
    element = self.driver.find_element(By.XPATH, "//dd[@id=\'모니터링\']/div/div/div/ul/a[3]/li/button/span/span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 52 | click | xpath=//dd[@id='모니터링']/div/div/div/ul/a[3]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'모니터링\']/div/div/div/ul/a[3]/li/button/span/span").click()
    # 53 | click | id=관리 | 
    self.driver.find_element(By.ID, "관리").click()
    # 54 | click | xpath=//dd[@id='관리']/div/div/div/ul/a/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'관리\']/div/div/div/ul/a/li/button/span/span").click()
    # 55 | mouseOver | css=.pf-m-focus .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".pf-m-focus .pf-c-menu__item-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 56 | mouseOut | css=.pf-m-focus .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 57 | click | xpath=//dd[@id='관리']/div/div/div/ul/a[2]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'관리\']/div/div/div/ul/a[2]/li/button/span/span").click()
    # 58 | click | xpath=//dd[@id='관리']/div/div/div/ul/a[3]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'관리\']/div/div/div/ul/a[3]/li/button/span/span").click()
    # 59 | mouseOver | xpath=//dd[@id='관리']/div/div/div/ul/a[3]/li/button/span/span | 
    element = self.driver.find_element(By.XPATH, "//dd[@id=\'관리\']/div/div/div/ul/a[3]/li/button/span/span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 60 | mouseOut | css=.pf-m-focus .pf-c-menu__item-text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 61 | click | css=.link-style:nth-child(4) .pf-c-menu__item | 
    self.driver.find_element(By.CSS_SELECTOR, ".link-style:nth-child(4) .pf-c-menu__item").click()
    # 62 | click | xpath=//dd[@id='관리']/div/div/div/ul/a[2]/li/button/span/span | 
    self.driver.find_element(By.XPATH, "//dd[@id=\'관리\']/div/div/div/ul/a[2]/li/button/span/span").click()
    # 63 | click | name=checkrow4 | 
    self.driver.find_element(By.NAME, "checkrow4").click()
  
